version: "3.8"

services:
  postgres:
    image: docker.io/postgres:16.1
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskdb
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
